=== oracle/database-navigator/src/main/java/com/dbn/language/common/definition/language-parser-elements-ext.dtd
<!--
  - Copyright 2026 Oracle and/or its affiliates
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  - https://www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -->

<!ELEMENT parser-element-extensions (one-of-extension)*>
<!ATTLIST parser-element-extensions
        language CDATA #REQUIRED
        source CDATA #REQUIRED
        builder-version CDATA #REQUIRED>

<!ELEMENT one-of-extension (node)*>
<!ATTLIST one-of-extension
        id CDATA #REQUIRED
        depth CDATA #REQUIRED>

<!ELEMENT node (node)*>
<!ATTLIST node
        id CDATA #IMPLIED
        ref CDATA #IMPLIED
        tt CDATA #IMPLIED
        pc CDATA #IMPLIED
        cc CDATA #IMPLIED>

=== oracle/database-navigator/src/main/java/com/dbn/language/sql/dialect/iso92/iso92_sql_parser_elements_ext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2026 Oracle and/or its affiliates
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<!--Generated with LanguageSpecificationParserExtensionBuilder. Do not edit manually.-->
<!DOCTYPE parser-element-extensions SYSTEM "../../../common/definition/language-parser-elements-ext.dtd">

<parser-element-extensions language="ISO92-SQL" source="iso92_sql_parser_elements.xml" builder-version="2.1.0">
    <one-of-extension id="00001" depth="2">
        <node tt="KW_SELECT, KW_VALUES" pc="query_expression" cc="00556, 00557, 00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00700, 00759, 00765, 00775, 00776, 00778, 00782, 00714, 00716, 00718, 00722, 00688, 00689" />
        <node tt="CHR_LEFT_PARENTHESIS" pc="query_expression" cc="00021, 00022" />
        <node tt="KW_DELETE" pc="delete_statement" cc="00053" />
        <node tt="KW_INSERT" pc="insert_statement" cc="00031" />
        <node tt="KW_UPDATE" pc="update_statement" cc="00610, 00611" />
        <node tt="KW_CREATE" pc="create_statement" cc="00211, 00306, 00321, 00341, 00353, 00358, 00372, 00388" />
        <node tt="KW_DROP" pc="drop_statement" cc="00399, 00401, 00406, 00408, 00411, 00414, 00417, 00419" />
        <node tt="KW_ALTER" pc="alter_statement" cc="00425, 00441" />
        <node tt="KW_DECLARE" pc="temporary_table_declaration, cursor_statement" cc="00293, 00061">
            <node tt="KW_LOCAL" pc="temporary_table_declaration" cc="00294" />
            <node tt="IDENTIFIER" pc="cursor_statement" cc="00065, 00066, 00067, 00069, 00071, 00062" />
        </node>
        <node tt="KW_COMMIT, KW_ROLLBACK" pc="transaction_control_statement" cc="00457, 00459" />
        <node tt="KW_SET" pc="transaction_control_statement, dynamic_sql_statement, connection_statement" cc="00461, 00482, 00488, 00497, 00499, 00502, 00504, 00182, 00183, 00184, 00185, 00201">
            <node tt="KW_TRANSACTION, KW_SESSION, KW_CONSTRAINTS, KW_CATALOG, KW_SCHEMA, KW_NAMES, DT_TIME" pc="transaction_control_statement" cc="00465, 00469, 00483, 00490, 00492, 00507, 00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00700, 00759, 00765, 00775, 00776, 00778, 00782, 00714, 00716, 00718, 00722, 00409, 00505" />
            <node id="N0000" tt="KW_GLOBAL, KW_LOCAL, KW_SQL, KW_DESCRIPTOR" pc="dynamic_sql_statement" cc="00184, 00185, 00186" />
            <node tt="KW_CONNECTION" pc="connection_statement" cc="00203, 00197" />
        </node>
        <node tt="KW_GET" pc="transaction_control_statement, dynamic_sql_statement" cc="00509, 00182, 00183, 00184, 00185">
            <node tt="KW_DIAGNOSTICS" pc="transaction_control_statement" cc="00937" />
            <node ref="N0000" />
        </node>
        <node tt="KW_GRANT, KW_REVOKE" pc="access_control_statement" cc="00533, 00537, 00538, 00539, 00541, 00542, 00543, 00526" />
        <node tt="KW_OPEN, KW_FETCH, KW_CLOSE" pc="cursor_statement" cc="00088, 00093, 00094, 00095, 00096, 00098, 00100, 00090, 00091, 00109" />
        <node tt="KW_PREPARE, KW_EXECUTE, KW_DESCRIBE, KW_ALLOCATE, KW_DEALLOCATE" pc="dynamic_sql_statement" cc="00113, 00114, 00119, 00125, 00126, 00175, 00176, 00177, 00178, 00171, 00182, 00183, 00184, 00185" />
        <node tt="KW_CONNECT, KW_DISCONNECT" pc="connection_statement" cc="00189, 00206, 00207, 00208, 00197" />
    </one-of-extension>
    <one-of-extension id="00035" depth="2">
        <node tt="KW_VALUES" pc="insert_values_clause, query_expression" cc="00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00700, 00759, 00765, 00775, 00776, 00778, 00782, 00714, 00716, 00718, 00722">
            <node tt="CHR_LEFT_PARENTHESIS" cc="00040, 00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00700, 00759, 00765, 00775, 00776, 00778, 00782, 00714, 00716, 00718, 00722, 00021, 00022" />
            <node tt="CHR_PLUS, CHR_MINUS, CHR_COLON" pc="query_expression" cc="00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00940, 00943" />
            <node tt="NUMBER, INTEGER, STRING, KW_NULL, KW_TRUE, KW_FALSE, VARIABLE, FN_CURRENT_USER, FN_SESSION_USER, FN_SYSTEM_USER, FN_USER, KW_VALUE, IDENTIFIER, FN_AVG, FN_COUNT, FN_MAX, FN_MIN, FN_SUM, KW_CASE, FN_NULLIF, KW_CAST, FN_EXTRACT, FN_POSITION, FN_CHARACTER_LENGTH, FN_CHAR_LENGTH, FN_OCTET_LENGTH, FN_BIT_LENGTH, FN_SUBSTRING, FN_TRIM, FN_UPPER, FN_LOWER, KW_CONVERT, KW_TRANSLATE, FN_CURRENT_DATE, FN_CURRENT_TIME, FN_CURRENT_TIMESTAMP, DT_INTERVAL" pc="query_expression" cc="00018, 00007, 00009, 00024, 00941, 00937, 00732, 00733, 00735, 00736, 00737, 00738, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00700, 00759, 00765, 00775, 00776, 00778, 00782, 00714, 00716, 00718, 00722, 00812, 00723" />
        </node>
        <node tt="KW_DEFAULT" pc="insert_default_values_clause" cc="00042" />
        <node tt="KW_SELECT" pc="query_expression" cc="00556, 00557, 00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00700, 00759, 00765, 00775, 00776, 00778, 00782, 00714, 00716, 00718, 00722, 00688, 00689" />
        <node tt="CHR_LEFT_PARENTHESIS" pc="query_expression" cc="00021, 00022" />
    </one-of-extension>
    <one-of-extension id="00105" depth="1">
        <node tt="VARIABLE" pc="parameter_specification" cc="00941, 00937" />
        <node tt="CHR_COLON" pc="parameter_specification, variable_specification" cc="00940, 00943" />
    </one-of-extension>
    <one-of-extension id="00106" depth="1">
        <node tt="NUMBER" pc="00107" />
        <node tt="VARIABLE" pc="parameter_specification" cc="00941, 00937" />
        <node tt="CHR_COLON" pc="parameter_specification, variable_specification" cc="00940, 00943" />
    </one-of-extension>
    <one-of-extension id="00110" depth="2">
        <node tt="KW_PREPARE" pc="prepare_statement" cc="00113" />
        <node tt="KW_EXECUTE" pc="execute_statement, execute_immediate_statement" cc="00114, 00119">
            <node tt="IDENTIFIER" pc="execute_statement" cc="00120" />
            <node tt="KW_IMMEDIATE" pc="execute_immediate_statement" cc="00116, 00937" />
        </node>
        <node tt="KW_DESCRIBE" pc="describe_statement" cc="00125, 00126, 00114" />
        <node tt="KW_ALLOCATE" pc="allocate_descriptor_statement" cc="00175, 00176, 00177, 00178" />
        <node tt="KW_SET" pc="set_descriptor_statement" cc="00182, 00183, 00184, 00185" />
        <node tt="KW_GET" pc="get_descriptor_statement" cc="00182, 00183, 00184, 00185" />
        <node tt="KW_DEALLOCATE" pc="deallocate_prepare_statement, deallocate_descriptor_statement" cc="00171, 00182, 00183, 00184, 00185">
            <node tt="KW_PREPARE" pc="deallocate_prepare_statement" cc="00114" />
            <node tt="KW_GLOBAL, KW_LOCAL, KW_SQL, KW_DESCRIPTOR" pc="deallocate_descriptor_statement" cc="00184, 00185, 00186" />
        </node>
    </one-of-extension>
    <one-of-extension id="00115" depth="1">
        <node tt="STRING" pc="00116" />
        <node tt="CHR_COLON" pc="variable_specification, parameter_specification" cc="00943, 00940" />
        <node tt="VARIABLE" pc="parameter_specification" cc="00941, 00937" />
    </one-of-extension>
    <one-of-extension id="00122" depth="4">
        <node tt="VARIABLE" pc="target_specification, value_expression" cc="00941, 00937">
            <node tt="KW_INDICATOR" cc="00937">
                <node id="N0001" tt="VARIABLE" pc="target_specification, value_expression">
                    <node id="N0002" tt="CHR_STAR, CHR_SLASH, CHR_PLUS, CHR_MINUS, OPR_CONCATENATION" pc="value_expression" cc="00732, 00733, 00735, 00736, 00737, 00738, 00937, 00931, 00932, 00933, 00934, 00935, 00691, 00692, 00693, 00694, 00795, 00796, 00797, 00798, 00799, 00803, 00790, 00814, 00800, 00740, 00747, 00752, 00753, 00755, 00757, 00722, 00700, 00759, 00765, 00775, 00776, 00778, 00782" />
                </node>
                <node id="N0003" tt="CHR_COLON" pc="target_specification, value_expression" cc="00940" />
            </node>
            <node ref="N0001" />
            <node ref="N0003" />
            <node ref="N0002" />
        </node>
        <node tt="CHR_COLON" pc="target_specification, value_expression" cc="00940, 00943" />
